# Generated by Django 5.2.3 on 2025-06-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('nombre', models.ManyToManyField(related_name='recetas', to='ComidasSemanales.comida')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad del ingrediente', max_digits=6)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComidasSemanales.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_en_receta', to='ComidasSemanales.receta')),
            ],
        ),
        migrations.CreateModel(
            name='ComidaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_semanales', to='ComidasSemanales.comida')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_semanales', to='ComidasSemanales.receta')),
            ],
        ),
    ]
