# Generated by Django 5.2.3 on 2025-06-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComidasSemanales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='receta',
            name='titulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='ComidasSemanales.comida'),
        ),
    ]
