# Generated by Django 5.2.3 on 2025-06-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Usuario', max_length=20)),
                ('apellido', models.CharField(help_text='Apellido del Usuario', max_length=20)),
                ('usuario', models.CharField(help_text='Nombre de Usuario', max_length=20)),
                ('contrasena', models.CharField(help_text='Contraseña del Usuario', max_length=20)),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['nombre', 'apellido'],
            },
        ),
    ]
